# Numpy


NumPy is a fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. NumPy is highly efficient, mainly due to its use of compiled C code.

NumPy is like a supercharged toolbox for handling numbers and doing math in Python. It's a library that makes it easier and faster to work with large sets of data, especially when you're dealing with numbers.

# Why do we use NumPy?
Efficiency: NumPy is super fast because it's written in a language called C, which is really good at crunching numbers quickly. This means you can do complex math operations on huge amounts of data without waiting forever.

Arrays: NumPy gives us a cool new data type called arrays. Think of arrays like fancy lists that can hold lots of numbers in a nice, organized way. Arrays make it easy to do math on whole sets of data all at once.

Math Functions: NumPy comes with tons of built-in math functions that work with arrays. Need to add up a bunch of numbers? NumPy's got you covered. Want to find the average of a set of values? NumPy can do that too, and much more!

# How do we use NumPy?
Install NumPy: First, you need to install NumPy on your computer. You can do this using a tool called pip, which comes with Python. Just type pip install numpy in your command prompt or terminal.

Import NumPy: Once NumPy is installed, you can start using it in your Python programs. You do this by typing import numpy as np at the top of your code. This tells Python that you want to use NumPy and that you'll refer to it as np to save typing.

Create Arrays: Now that NumPy is ready to go, you can create arrays using the np.array() function. You just pass in a list of numbers, and NumPy will turn it into an array for you.

Do Math: With your arrays all set up, you can start doing math with them! NumPy lets you add, subtract, multiply, and divide arrays just like you would with regular numbers.

Explore: NumPy has lots of other cool features too, like slicing and indexing arrays, reshaping them, and even fancy stuff like Fourier transforms. The more you explore, the more you'll discover what NumPy can do!

Data Type:
List: Can store different data types in a single list.
Numpy Array: Stores elements of the same data type for more efficient computation.


Performance:
List: Slower for numerical operations due to generic data type handling.
Numpy Array: Faster for numerical operations due to optimized C-based implementation.


3. Functionality:

List: Limited built-in functions for numerical operations.
Numpy Array: Rich set of built-in functions for complex numerical operations.


4. Memory Usage:

List: Consumes more memory as it stores both data and type information.
Numpy Array: More memory-efficient, storing only data with uniform type.


5. Broadcasting:

List: Does not support broadcasting; element-wise operations require explicit loops.
Numpy Array: Supports broadcasting, allowing element-wise operations without explicit loops.

In [1]:
a = [1,2,3,4,5,6,7,8,9,10]

In [2]:
print(a+2)

TypeError: can only concatenate list (not "int") to list

In [5]:
print(a*2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
pip install numpy 

In [6]:
import numpy as np 

In [7]:
np.__version__

'1.23.5'

In [8]:
data = [1,"Hello","Python","3+4j",True,45.35]

array = np.array(data)

array

array(['1', 'Hello', 'Python', '3+4j', 'True', '45.35'], dtype='<U32')

In [12]:
a = [12.4,63.2,34,23,10,56.3,34,10.5] # does not mantain order and unique elements

print(a,type(a))

array = np.array(a)

print(array,type(array),id(array))


[12.4, 63.2, 34, 23, 10, 56.3, 34, 10.5] <class 'list'>
[12.4 63.2 34.  23.  10.  56.3 34.  10.5] <class 'numpy.ndarray'> 2641846747664


In [14]:
a = [1,2,3,4,5,6,7,8,9,10]

array = np.array(a)

print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
array.ndim

1

In [16]:
array.size

10

In [18]:
val = list(range(1,21,2))

array = np.array(val)

array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [21]:
array  = np.arange(2,20,3,dtype=float)
print(array)

[ 2.  5.  8. 11. 14. 17.]


In [22]:
data = [[1,2,3],[4,5,6],[7,8,9]]

array = np.array(data)

print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
array.ndim

2

In [26]:
array.shape

(3, 3)

In [25]:
array.size

9

In [30]:
ones_array  = np.ones((4,4),dtype = int)
print(ones_array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [31]:
zeros_array  = np.zeros((4,4),dtype = int)
print(zeros_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [34]:
eye_array  = np.eye(4,dtype = int)
print(eye_array)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [39]:
array = np.diag((31,31))
array

array([[31,  0],
       [ 0, 31]])

In [40]:
data = np.diagonal(array)
data

array([31, 31])

In [50]:
array = np.random.randint(2,30,size=(4,4),dtype=int)
print(array)

[[13 23 24  8]
 [24 27 13 16]
 [ 6 26 22  5]
 [11  4  2  5]]


In [52]:
array = np.full((3,3),10)
array


array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [55]:
array = np.random.randint(2,30,size=(5,5),dtype=int)
print(array)

[[28 13 14 12  5]
 [29 28  7 26 18]
 [10  9 23  8 29]
 [ 6 22 29 13 17]
 [ 6  8 22 17 20]]


In [54]:
array[2]

array([25,  8, 26,  7])

In [56]:
array[1:3]

array([[29, 28,  7, 26, 18],
       [10,  9, 23,  8, 29]])

In [57]:
array[1:4,2]

array([ 7, 23, 29])

In [58]:
array[1:4,1:3] = 45

In [59]:
array

array([[28, 13, 14, 12,  5],
       [29, 45, 45, 26, 18],
       [10, 45, 45,  8, 29],
       [ 6, 45, 45, 13, 17],
       [ 6,  8, 22, 17, 20]])

In [61]:
array[:,2:4]

array([[14, 12],
       [45, 26],
       [45,  8],
       [45, 13],
       [22, 17]])

In [63]:
array[2:4,:]

array([[10, 45, 45,  8, 29],
       [ 6, 45, 45, 13, 17]])

In [ ]:
array[row_slicing,columns_slicing]

In [64]:
array[2][1]

45

In [65]:
array[2,1]

45

In [66]:
array

array([[28, 13, 14, 12,  5],
       [29, 45, 45, 26, 18],
       [10, 45, 45,  8, 29],
       [ 6, 45, 45, 13, 17],
       [ 6,  8, 22, 17, 20]])

In [67]:
array[1:4:2,:]

array([[29, 45, 45, 26, 18],
       [ 6, 45, 45, 13, 17]])

In [68]:
array[[1,4]]

array([[29, 45, 45, 26, 18],
       [ 6,  8, 22, 17, 20]])

In [69]:
array[[0,-1]]

array([[28, 13, 14, 12,  5],
       [ 6,  8, 22, 17, 20]])

In [70]:
array

array([[28, 13, 14, 12,  5],
       [29, 45, 45, 26, 18],
       [10, 45, 45,  8, 29],
       [ 6, 45, 45, 13, 17],
       [ 6,  8, 22, 17, 20]])

In [71]:
array+10

array([[38, 23, 24, 22, 15],
       [39, 55, 55, 36, 28],
       [20, 55, 55, 18, 39],
       [16, 55, 55, 23, 27],
       [16, 18, 32, 27, 30]])

In [72]:
array**2

array([[ 784,  169,  196,  144,   25],
       [ 841, 2025, 2025,  676,  324],
       [ 100, 2025, 2025,   64,  841],
       [  36, 2025, 2025,  169,  289],
       [  36,   64,  484,  289,  400]])

In [73]:
array

array([[28, 13, 14, 12,  5],
       [29, 45, 45, 26, 18],
       [10, 45, 45,  8, 29],
       [ 6, 45, 45, 13, 17],
       [ 6,  8, 22, 17, 20]])

In [74]:
array % 2 == 0

array([[ True, False,  True,  True, False],
       [False, False, False,  True,  True],
       [ True, False, False,  True, False],
       [ True, False, False, False, False],
       [ True,  True,  True, False,  True]])

In [77]:
array[array % 2 == 0]

array([28, 14, 12, 26, 18, 10,  8,  6,  6,  8, 22, 20])

In [78]:
equalspace = np.linspace(10,100,10)
equalspace

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [83]:
equalspace = np.linspace(3,10,10)
equalspace

array([ 3.        ,  3.77777778,  4.55555556,  5.33333333,  6.11111111,
        6.88888889,  7.66666667,  8.44444444,  9.22222222, 10.        ])

In [82]:
array

array([[28, 13, 14, 12,  5],
       [29, 45, 45, 26, 18],
       [10, 45, 45,  8, 29],
       [ 6, 45, 45, 13, 17],
       [ 6,  8, 22, 17, 20]])

In [84]:
array = np.random.randint(2,30,size=(3,3),dtype=int)
print(array)

[[10 25 24]
 [ 6 18 29]
 [27 28 12]]


axis=0 refers to operations along the rows (i.e., down the columns, vertically). 

If you sum with axis=0, it adds the values column-wise.

axis=1 refers to operations along the columns (i.e., across the rows, horizontally). 

If you sum with axis=1, it adds the values row-wise.

In [86]:
array.sum()

179

In [88]:
np.sum(array,axis = 1)

array([59, 53, 67])

In [91]:
np.sum(array,axis = 0)

array([43, 71, 65])

In [92]:
array.min()

6

In [93]:
np.min(array,axis = 1)

array([10,  6, 12])

In [94]:
np.min(array,axis = 0)

array([ 6, 18, 12])

In [121]:
array.max()

29

In [122]:
np.max(array,axis = 1)

array([25, 29, 28])

In [123]:
np.max(array,axis = 1)

array([25, 29, 28])

In [95]:
np.mean(array,axis = 1)

array([19.66666667, 17.66666667, 22.33333333])

In [97]:
array.mean()

19.88888888888889

In [98]:
np.mean(array,axis = 0)

array([14.33333333, 23.66666667, 21.66666667])

In [99]:
array**0.5

array([[3.16227766, 5.        , 4.89897949],
       [2.44948974, 4.24264069, 5.38516481],
       [5.19615242, 5.29150262, 3.46410162]])

In [101]:
np.sqrt(array)

array([[3.16227766, 5.        , 4.89897949],
       [2.44948974, 4.24264069, 5.38516481],
       [5.19615242, 5.29150262, 3.46410162]])

In [102]:
np.median(array)

24.0

In [103]:
array

array([[10, 25, 24],
       [ 6, 18, 29],
       [27, 28, 12]])

The median is the middle value in a sorted set of numbers. It divides the dataset into two equal halves half the numbers are smaller than the median, and half are larger.

How to find the median:

Sort the numbers in ascending order (if not already sorted):

10, 25, 24,6, 18, 29,27, 28, 12

6,10,12,19,24,25,27,28,29

Count the total number of values (here, there are 9 numbers).

Find the position of the median:

The formula to find the position is: 
(𝑛+1)/2

(n+1)/2, where 𝑛 is the total number of values.

Here, 𝑛=9
n=9, so (9+1)/2=10/2=5

Locate the 5th value in the sorted list, which is 24.

In [104]:
np.std(array)

8.157402152434512

In [105]:
np.var(array)

66.5432098765432

In [106]:
66**0.5

8.12403840463596

In [107]:
array

array([[10, 25, 24],
       [ 6, 18, 29],
       [27, 28, 12]])

In [108]:
onedarray = np.ravel(array)
onedarray

array([10, 25, 24,  6, 18, 29, 27, 28, 12])

In [109]:
array

array([[10, 25, 24],
       [ 6, 18, 29],
       [27, 28, 12]])

In [111]:
array = np.random.randint(2,30,size=(4,4),dtype=int)
print(array)

[[27 21 18 18]
 [17 19 28 22]
 [10 22 23 12]
 [ 4 20  7  2]]


In [113]:
array.shape

(4, 4)

In [114]:
reshaped = np.reshape(array,(2,8)) # 5*5 = 25 16
reshaped 

array([[27, 21, 18, 18, 17, 19, 28, 22],
       [10, 22, 23, 12,  4, 20,  7,  2]])

In [115]:
reshaped = np.reshape(array,(8,2)) # 5*5 = 25 16
reshaped 

array([[27, 21],
       [18, 18],
       [17, 19],
       [28, 22],
       [10, 22],
       [23, 12],
       [ 4, 20],
       [ 7,  2]])

In [116]:
reshaped = np.reshape(array,(5,5)) # 5*5 = 25 16
reshaped 

ValueError: cannot reshape array of size 16 into shape (5,5)

In [118]:
reshaped = np.reshape(array,(16,1)) # 5*5 = 25 16
reshaped 

array([[27],
       [21],
       [18],
       [18],
       [17],
       [19],
       [28],
       [22],
       [10],
       [22],
       [23],
       [12],
       [ 4],
       [20],
       [ 7],
       [ 2]])