In [3]:
import numpy as np

In [15]:
array1=np.random.randint(1,15, size=(3,3))

array1

array([[ 2,  9, 13],
       [12, 12,  3],
       [ 6, 11,  5]])

In [17]:
array2=np.random.randint(15,30, size=(3,3))

array2

array([[17, 29, 27],
       [27, 18, 21],
       [16, 19, 18]])

In [25]:
array3=np.append(array1,array2,axis=0)

array3

array([[ 2,  9, 13],
       [12, 12,  3],
       [ 6, 11,  5],
       [17, 29, 27],
       [27, 18, 21],
       [16, 19, 18]])

In [29]:
a=np.concatenate((array1,array2),axis=0)

a

array([[ 2,  9, 13],
       [12, 12,  3],
       [ 6, 11,  5],
       [17, 29, 27],
       [27, 18, 21],
       [16, 19, 18]])

In [31]:
b=np.hstack((array1,array2))

b

array([[ 2,  9, 13, 17, 29, 27],
       [12, 12,  3, 27, 18, 21],
       [ 6, 11,  5, 16, 19, 18]])

In [33]:
b=np.vstack((array1,array2))

b

array([[ 2,  9, 13],
       [12, 12,  3],
       [ 6, 11,  5],
       [17, 29, 27],
       [27, 18, 21],
       [16, 19, 18]])

In [35]:
a=[1,2,3,4,5,6,7,8,9]

array=np.array(a)

array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
b=np.flip(array)

b

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [39]:
array1=np.random.randint(1,10,size=(3,3))

array1

array([[7, 8, 7],
       [9, 6, 2],
       [2, 6, 2]])

In [41]:
array2=np.random.randint(1,10,size=(3,3))

array2

array([[4, 8, 9],
       [3, 8, 4],
       [6, 3, 2]])

In [43]:
a=np.equal(array1,array2)
a

array([[False,  True, False],
       [False, False, False],
       [False, False,  True]])

In [47]:
b=array1[array1>array2]

b

array([7, 9, 6])

In [49]:
bool_result=np.where(a>0,1,0)

bool_result

array([[0, 1, 0],
       [0, 0, 0],
       [0, 0, 1]])

In [51]:
array1

array([[7, 8, 7],
       [9, 6, 2],
       [2, 6, 2]])

In [63]:
data=np.array([1,2,3])

In [65]:
result=np.append(array1,[data],axis=0)

result

array([[7, 8, 7],
       [9, 6, 2],
       [2, 6, 2],
       [1, 2, 3]])

In [67]:
array=np.array([[2,3,np.nan],[4,np.nan,6],[np.nan,6,7]])

array

array([[ 2.,  3., nan],
       [ 4., nan,  6.],
       [nan,  6.,  7.]])

In [69]:
np.isnan(array)

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False]])

In [73]:
np.isnan(array).sum()

3

In [77]:
cumulative_sum=np.array([2,3,4,5,6,3,4,2,7,8,9])

cumulative_sum

array([2, 3, 4, 5, 6, 3, 4, 2, 7, 8, 9])

In [79]:
a=np.cumsum(cumulative_sum)

a

array([ 2,  5,  9, 14, 20, 23, 27, 29, 36, 44, 53])

In [81]:
np.bincount(cumulative_sum)

array([0, 0, 2, 2, 2, 1, 1, 1, 1, 1], dtype=int64)

In [83]:
product=np.product(cumulative_sum)

product

8709120

In [87]:
array1=np.array([2,3,4])

array2=np.array([5,6,7])

result=np.cross(array1,array2)

result

array([-3,  6, -3])

In [ ]:
a=np.