In [5]:
import numpy as np

In [9]:
a=[[ 1,2,3],[4,5,6],[6,7,8]]

array= np.array(a)

print(array)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [11]:
array.ndim

2

In [13]:
array.size

9

In [15]:
array.shape

(3, 3)

In [17]:
data=[1,2,3,4,5,6]

array=np.array(data)

print(data)

[1, 2, 3, 4, 5, 6]


In [19]:
random_array=np.random.randint(2,10,size=(3,3))

print(random_array)

[[9 9 7]
 [8 2 7]
 [4 6 4]]


In [45]:
random_array=np.random.randint(1,10,size=(5,5))

print(random_array)

[[9 2 1 6 6]
 [6 7 9 3 1]
 [8 2 5 2 1]
 [5 5 3 2 9]
 [2 1 5 2 4]]


In [47]:
print(random_array[2])

[8 2 5 2 1]


In [49]:
print(random_array[2:4])

[[8 2 5 2 1]
 [5 5 3 2 9]]


In [51]:
print(random_array[2:4,2])

[5 3]


In [53]:
print(random_array[1:3,1:3])

[[7 9]
 [2 5]]


In [55]:
random_array.sum()

106

In [57]:
random_array.min()

1

In [59]:
random_array.std()

2.657517638699695

In [61]:
random_array.var()

7.062400000000001

In [63]:
random_array.max()

9

In [65]:
np.sum(random_array,axis=1)

array([24, 26, 18, 24, 14])

In [67]:
np.sum(random_array,axis=0)

array([30, 17, 23, 15, 21])

In [69]:
np.max(random_array,axis=1)

array([9, 9, 8, 9, 5])

In [71]:
np.max(random_array,axis=0)

array([9, 7, 9, 6, 9])

In [73]:
np.average(random_array,axis=1)

array([4.8, 5.2, 3.6, 4.8, 2.8])

In [75]:
np.sort(random_array)

array([[1, 2, 6, 6, 9],
       [1, 3, 6, 7, 9],
       [1, 2, 2, 5, 8],
       [2, 3, 5, 5, 9],
       [1, 2, 2, 4, 5]])

In [83]:
array=np.reshape(random_array,(1,25))
array

array([[9, 2, 1, 6, 6, 6, 7, 9, 3, 1, 8, 2, 5, 2, 1, 5, 5, 3, 2, 9, 2, 1,
        5, 2, 4]])

In [93]:
array=np.reshape(random_array,(5,5))
array

array([[9, 2, 1, 6, 6],
       [6, 7, 9, 3, 1],
       [8, 2, 5, 2, 1],
       [5, 5, 3, 2, 9],
       [2, 1, 5, 2, 4]])

In [97]:
one_D=np.ravel(random_array)
one_D

array([9, 2, 1, 6, 6, 6, 7, 9, 3, 1, 8, 2, 5, 2, 1, 5, 5, 3, 2, 9, 2, 1,
       5, 2, 4])

In [99]:
np.sqrt(random_array)

array([[3.        , 1.41421356, 1.        , 2.44948974, 2.44948974],
       [2.44948974, 2.64575131, 3.        , 1.73205081, 1.        ],
       [2.82842712, 1.41421356, 2.23606798, 1.41421356, 1.        ],
       [2.23606798, 2.23606798, 1.73205081, 1.41421356, 3.        ],
       [1.41421356, 1.        , 2.23606798, 1.41421356, 2.        ]])

In [103]:
np.power(random_array,2)

array([[81,  4,  1, 36, 36],
       [36, 49, 81,  9,  1],
       [64,  4, 25,  4,  1],
       [25, 25,  9,  4, 81],
       [ 4,  1, 25,  4, 16]], dtype=int32)

In [107]:
np.sort(random_array)

array([[1, 2, 6, 6, 9],
       [1, 3, 6, 7, 9],
       [1, 2, 2, 5, 8],
       [2, 3, 5, 5, 9],
       [1, 2, 2, 4, 5]])